name: Publish new Docker image to GHCR
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: vlazdra/firebase-distribution-github-action:latest
# jobs:
#   publish-docker-image:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the repository
#         uses: actions/checkout@v3
#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v2
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Firebase-Distribution-GitHub-Action Docker image
#         run: |
#             docker build -t ghcr.io/vlazdra/firebase-distribution-github-action -f Dockerfile .
#             docker push ghcr.io/vlazdra/firebase-distribution-github-action:latest