name: Publish new Docker image to GHCR
on:
  push:
    branches:
      - master
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
            image-name: docker-image # Provide Docker image name
            additional-image-tags: v1.0.2